config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#top'
  get 'static_pages/terms', as: :terms
  get 'static_pages/privacy', as: :privacy
  get 'login', to: 'user_sessions#new', as: :login
  post 'login', to: "user_sessions#create"
  delete 'logout', to: 'user_sessions#destroy', as: :logout
  get 'results', to: "results#index"
  get 'rankings', to: "rankings#index"
  post '/google_login/callback', to: 'google_login#callback'

  resources :users
  get 'users/:id/change_password', to: "users#change_password", as: :change_password

  resources :password_resets, only: %i[new create edit update]

  resources :recordings, only: %i[new create] do
    resources :text_analyses, only: %i[new create]
    resources :results, only: %i[new create show]
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login, only: %i[top terms privacy]
  skip_before_action :require_account, only: %i[top terms privacy]

  def top
  end

  def terms
  end

  def privacy
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/privacy.html.erb
<% content_for(:title, t('.title')) %>

<div class="container">
  <div>
    <p class="h2 mt-5">プライバシーポリシー</p>
  </div>

  <div class="mt-5">
    <p class="h4">取得する情報</p>
    <p>本サービスはユーザーから以下の情報を取得します。</p>
    <ul>
      <li>外部サービスのプライバシー設定によりユーザーが連携先に開示を認めた情報</li>
      <li>Cookie（クッキー）を用いて生成された識別情報</li>
      <li>OSが生成するID、端末の種類、端末識別子等のユーザーが利用するOSや端末に関する情報</li>
      <li>本ウェブサイトの滞在時間、入力履歴等の本ウェブサイトにおけるユーザーの行動履歴</li>
      <li>ユーザーの音声データ</li>
    </ul>
  </div>

  <div>
    <p class="h4">情報を利用する目的</p>
    <p>本サービスは、ユーザーから取得した情報を以下の目的のために利用します。</p>
    <ul>
      <li>ユーザーの本サービスの利用履歴を管理するため</li>
      <li>本サービスにおけるユーザーの行動履歴を分析し、本サービスの維持改善に役立てるため</li>
      <li>市場分析、マーケティングのため</li>
      <li>ユーザーからのお問い合わせに対応するため</li>
      <li>本サービスの利用規約や法令に違反する行為に対応するため</li>
      <li>以上の他、当社サービスの提供、維持、保護及び改善のため</li>
    </ul>
  </div>

  <div>
    <p class="h4">第三者提供</p>
    <p>本サービスは、ユーザーから取得する情報のうち、個人データ（個人情報保護法第２条第６項）に該当するものついては、あらかじめユーザーの同意を得ずに、第三者（日本国外にある者を含みます。）に提供しません。<br>
    但し、次の場合は除きます。</p>
    <ul>
      <li>個人データの取扱いを外部に委託する場合</li>
      <li>本サービスが買収された場合</li>
      <li>事業パートナーと共同利用する場合（具体的な共同利用がある場合は、その内容を別途公表します。）</li>
      <li>その他、法律によって合法的に第三者提供が許されている場合</li>
    </ul>
  </div>

  <div>
    <p class="h4">アクセス解析ツール</p>
    <p>本サービスは、ユーザーのアクセス解析のために、「Googleアナリティクス」を利用しています。Googleアナリティクスは、トラフィックデータの収集のためにCookieを使用しています。トラフィックデータは匿名で収集されており、個人を特定するものではありません。Cookieを無効にすれば、これらの情報の収集を拒否することができます。詳しくはお使いのブラウザの設定をご確認ください。Googleアナリティクスについて、詳しくは以下からご確認ください。</p>
    <p><%= link_to 'Google アナリティクス利用規約', 'https://marketingplatform.google.com/about/analytics/terms/jp/', target: '_blank' %></p>
  </div>

  <div>
    <p class="h4">プライバシーポリシーの変更</p>
    <p>本サービスは、必要に応じて、このプライバシーポリシーの内容を変更します。</p>
  </div>

  <div>
    <p class="h4">お問い合わせ</p>
    <p>お客様の情報の開示、情報の訂正、利用停止、削除をご希望の場合は、以下のTwitterアカウント宛にダイレクトメールにてご連絡ください。</p>
    <p>Twitter ID : <%= link_to '@shap42103', 'https://twitter.com/shap42103' %></p>
  </div>

  <div>
    <p>2022年10月6日制定</p>
  </div>
</div>

app/views/static_pages/terms.html.erb
<% content_for(:title, t('.title')) %>

<div class="container">
  <div>
    <p class="h2 mt-5">利用規約</p>
    <p>この利用規約（以下、「本規約」といいます。）は、本ウェブサイトの管理者（以下、「管理者」といいます。）が本ウェブサイト上で提供するサービス（以下、「本サービス」といいます。）の利用条件を定めるものです。ユーザーは、本サービスの利用を開始した時点で、本規約の全ての記載内容について同意したものとみなされます。</p>
  </div>

  <div class="mt-5">
    <p class="h4">第1条（適用）</p>
    <ol>
      <li>本規約は、ユーザーと本サービス提供者との間の本サービスの利用に関わる一切の関係に適用されるものとします。</li>
      <li>管理者は本サービスに関し、本規約のほか、ご利用にあたってのルール等、各種の定め（以下、「個別規定」といいます。）をすることがあります。これら個別規定はその名称の如何に関わらず、本規約の一部を構成するものとします。</li>
      <li>本規約の規定が前条の個別規定の規定と矛盾する場合には、個別規定において特段の定めなき限り、個別規定の規定が優先されるものとします。</li>
    </ol>
  </div>

  <div>
    <p class="h4">第2条（禁止事項）</p>
    <p>ユーザーは、本サービスの利用にあたり、以下の行為をしてはなりません。</p>
    <ol>
      <li>法令または公序良俗に違反する行為</li>
      <li>犯罪行為に関連する行為</li>
      <li>管理者、本サービスの他のユーザー、または第三者のサーバーまたはネットワークの機能を破壊したり、妨害したりする行為</li>
      <li>管理者のサービスの運営を妨害するおそれのある行為</li>
      <li>他のユーザーに関する個人情報等を収集または蓄積する行為</li>
      <li>不正アクセスをし、またはこれを試みる行為</li>
      <li>他のユーザーに成りすます行為</li>
      <li>管理者のサービスに関連して、反社会的勢力に対して直接または間接に利益を供与する行為</li>
      <li>管理者、本サービスの他のユーザーまたは第三者の知的財産権、肖像権、プライバシー、名誉その他の権利または利益を侵害する行為</li>
      <li>以下の表現を含み、または含むと管理者が判断する内容を本サービス上に投稿し、または送信する行為</li>
      <ol>
        <li>過度に暴力的な表現</li>
        <li>露骨な性的表現</li>
        <li>人種、国籍、信条、性別、社会的身分、門地等による差別につながる表現</li>
        <li>自殺、自傷行為、薬物乱用を誘引または助長する表現</li>
        <li>その他反社会的な内容を含み他人に不快感を与える表現</li>
      </ol>
      <li>以下を目的とし、または目的とすると管理者が判断する行為</li>
      <ol>
        <li>営業、宣伝、広告、勧誘、その他営利を目的とする行為（管理者の認めたものを除きます。）</li>
        <li>性行為やわいせつな行為を目的とする行為</li>
        <li>面識のない異性との出会いや交際を目的とする行為</li>
        <li>他のユーザーに対する嫌がらせや誹謗中傷を目的とする行為</li>
        <li>管理者、本サービスの他のユーザー、または第三者に不利益、損害または不快感を与えることを目的とする行為</li>
        <li>その他本サービスが予定している利用目的と異なる目的で本サービスを利用する行為</li>
      </ol>
      <li>宗教活動または宗教団体への勧誘行為</li>
      <li>その他、管理者が不適切と判断する行為</li>
    </ol>
  </div>

  <div>
    <p class="h4">第3条（本サービスの提供の停止等）</p>
    <ol>
      <li>管理者は、以下のいずれかの事由があると判断した場合、ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。</li>
      <ol>
        <li>本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</li>
        <li>地震、落雷、火災、停電または天災などの不可抗力により、本サービスの提供が困難となった場合</li>
        <li>コンピュータまたは通信回線等が事故により停止した場合</li>
        <li>その他、管理者が本サービスの提供が困難と判断した場合</li>
      </ol>
      <li>管理者は、本サービスの提供の停止または中断により、ユーザーまたは第三者が被ったいかなる不利益または損害についても、一切の責任を負わないものとします。</li>
    </ol>
  </div>

  <div>
    <p class="h4">第4条（著作権）</p>
    <ol>
      <li>ユーザーは、自ら著作権等の必要な知的財産権を有するか、または必要な権利者の許諾を得た音声等の情報に関してのみ、本サービスを利用し、投稿ないしアップロードすることができるものとします。</li>
      <li>ユーザーが本サービスを利用して投稿ないしアップロードした音声等の著作権については、当該ユーザーその他既存の権利者に留保されるものとします。ただし、管理者は、本サービスを利用して投稿ないしアップロードされた音声等について、本サービスの改良、品質の向上、または不備の是正等ならびに本サービスの周知宣伝等に必要な範囲で利用できるものとし、ユーザーは、この利用に関して、著作者人格権を行使しないものとします。</li>
      <li>前項本文の定めるものを除き、本サービスおよび本サービスに関連する一切の情報についての著作権およびその他の知的財産権はすべて管理者または管理者にその利用を許諾した権利者に帰属し、ユーザーは無断で複製、譲渡、貸与、翻訳、改変、転載、公衆送信（送信可能化を含みます。）、伝送、配布、出版、営業使用等をしてはならないものとします。</li>
    </ol>
  </div>

  <div>
    <p class="h4">第5条（利用制限）</p>
    <ol>
      <li>管理者は、ユーザーが以下のいずれかに該当する場合には、事前の通知なく投稿データを削除し、ユーザーに対して本サービスの全部もしくは一部の利用を制限できるものとします。</li>
      <ol>
        <li>本規約のいずれかの条項に違反した場合</li>
        <li>その他、管理者が本サービスの利用を適当でないと判断した場合</li>
      </ol>
      <li>管理者は、本条に基づき管理者が行った行為によりユーザーに生じた損害について、一切の責任を負いません。</li>
    </ol>
  </div>

  <div>
    <p class="h4">第6条（保証の否認および免責事項）</p>
    <ol>
      <li>管理者は、本サービスに事実上または法律上の瑕疵（安全性、信頼性、正確性、完全性、有効性、特定の目的への適合性、セキュリティなどに関する欠陥、エラーやバグ、権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。</li>
      <li>管理者は、本サービスに起因してユーザーに生じたあらゆる損害について一切の責任を負いません。ただし、本サービスに関する管理者とユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合、この免責規定は適用されません。</li>
      <li>前項ただし書に定める場合であっても、管理者は、管理者の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（管理者またはユーザーが損害発生につき予見し、または予見し得た場合を含みます。）について一切の責任を負いません。また、管理者の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害の賠償は、ユーザーから当該損害が発生した月に受領した利用料の額を上限とします。</li>
      <li>管理者は、本サービスに関して、ユーザーと他のユーザーまたは第三者との間において生じた取引、連絡または紛争等について一切責任を負いません。</li>
    </ol>
  </div>

  <div>
    <p class="h4">第7条（サービス内容の変更等）</p>
    <p>管理者は、ユーザーに通知することなく、本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし、これによってユーザーに生じた損害について一切の責任を負いません。</p>
  </div>

  <div>
    <p class="h4">第8条（利用規約の変更）</p>
    <p>管理者は、必要と判断した場合には、ユーザーに通知することなくいつでも本規約を変更することができるものとします。なお、本規約の変更後、本サービスの利用を開始した場合には、当該ユーザーは変更後の規約に同意したものとみなします。</p>
  </div>

  <div>
    <p class="h4">第9条（個人情報の取扱い）</p>
    <p>管理者は、本サービスの利用によって取得する個人情報については、管理者「プライバシーポリシー」に従い適切に取り扱うものとします。</p>
  </div>

  <div>
    <p class="h4">第10条（権利義務の譲渡の禁止）</p>
    <p>ユーザーは、管理者の書面による事前の承諾なく、利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し、または担保に供することはできません。</p>
  </div>

  <div>
    <p class="h4">第11条（準拠法・裁判管轄）</p>
    <ol>
      <li>本規約の解釈にあたっては、日本法を準拠法とします。</li>
      <li>本サービスに関して紛争が生じた場合には、管理者の本店所在地を管轄する裁判所を専属的合意管轄とします。</li>
    </ol>
  </div>

  <div>
    <p>以上</p>
    <p>2022年10月6日制定</p>
  </div>
</div>

app/views/static_pages/top.html.erb
<div class="main-color blur">
  <div id="slogan" class="container mx-auto row">
    <div class="col-md-6 col-sm-12 d-flex align-items-center">
      <div class="d-flex flex-column">
        <div class="mb-2">
          <p class="h1">えっと、あのー…</p>
          <p class="h1">無意識に出てしまう</p>
          <p class="h1">そんな言葉を見える化</p>
        </div>
        <div>
          <p class="mb-1">フィラーと呼ばれるこれらの言葉をなくして</p>
          <p>スピーチの印象アップをしましょう！</p>
        </div>
        <div>
          <%= link_to t('defaults.challenge'), new_recording_path, class: 'btn btn-warning btn-circle' %>
          <%= link_to t('defaults.show_everyone_results'), rankings_path, class: 'btn btn-info btn-circle ms-1' %>
        </div>
      </div>
    </div>
    <div class="col-md-6 col-sm-12 d-flex">
      <%= image_tag 'before_after', class: "img-fluid m-3" %>
    </div>
  </div>
</div>

<div class="container mx-auto mb-3">
  <div id="recommend-for" class="row mt-5">
    <p class="h2 text-center">こんなひとにおすすめ</p>
    <div class="row d-flex justify-content-between mt-3">
      <div class="col-4 d-flex flex-column align-items-center">
        <%= image_tag 'doyagao_man', class: "img-fluid rounded-circle border border-2 col-10 mb-2" %>
        <div class="h3 text-center">
          <p class="mb-0">もっとスムーズに</p>
          <p class="mb-1">話せるようになりたい</p>
        </div>
        <div class="text-center">
          <p class="mb-0">どのくらい言葉に詰まってしまう？</p>
          <p>現状把握をしてみましょう</p>
        </div>
      </div>
      <div class="col-4 d-flex flex-column align-items-center">
        <%= image_tag 'explaining_man', class: "img-fluid rounded-circle border border-2 col-10 mb-2" %>
        <div class="h3 text-center">
          <p class="mb-0">好印象な</p>
          <p class="mb-1">プレゼンがしたい</p>
        </div>
        <div class="text-center">
          <p class="mb-0">フィラーを減らすためにはどうすれば？</p>
          <p>テクニックを身につけましょう</p>
        </div>
      </div>
      <div class="col-4 d-flex flex-column align-items-center">
        <%= image_tag 'worried_woman', class: "img-fluid rounded-circle border border-2 col-10 mb-2" %>
        <div class="h3 text-center">
          <p class="mb-0">説明することに</p>
          <p class="mb-1">慣れていない</p>
        </div>
        <div class="text-center">
          <p class="mb-0">いざ説明しようとすると緊張する？</p>
          <p>経験を自信につなげましょう</p>
        </div>
      </div>
    </div>
  </div>

  <div id="how-to-use" class="row mt-5">
    <p class="h2 text-center">本サービスの使い方</p>
    <div class="row d-flex justify-content-center mt-3 border border-2">
      <%= image_tag 'how_to_rec', class: "img-fluid col-md-3 col-6 m-2 blur" %>
      <div class="col-md-6 mt-3">
        <p class="h3 mb-4">話題に沿って語ってみましょう</p>
        <p class="mb-1">テーマを選んだら早速 "録音を開始"</p>
        <p class="mb-1">まずは上手に話そうと意識する必要はありません！</p>
        <p class="mb-1">ありのまま自分の考えを語ってみましょう</p>
      </div>
    </div>
    <div class="row d-flex justify-content-center border border-2">
      <div class="col-md-6 mt-3">
        <p class="h3 mb-4">分析結果を記録しながら練習しましょう</p>
        <p class="mb-1">結果を確認してあなたのフィラー癖を見える化</p>
        <p class="mb-1">マイページではフィラー頻度をグラフで管理し</p>
        <p class="mb-1">練習の成果がひと目で確認できます！</p>
      </div>
      <%= image_tag 'show_result', class: "img-fluid col-md-3 col-6 m-2 blur" %>
    </div>
    <div class="row d-flex justify-content-center border border-2">
      <%= image_tag 'result_ranking', class: "img-fluid col-md-3 col-6 m-2 blur" %>
      <div class="col-md-6 col-xs-12 mt-3">
        <p class="h3 mb-4">他のユーザーと結果をシェアしましょう</p>
        <p class="mb-1">登録ユーザーのフィラー頻度をテーマごとにランキング表示</p>
        <p class="mb-1">SNSへの投稿もしてみましょう！</p>
        <p class="mb-1">※シェア機能は今後実装予定です</p>
      </div>
    </div>

    <div class="d-flex justify-content-center mt-3">
      <%= link_to t('defaults.challenge'), new_recording_path, class: 'btn btn-warning col-4' %>
    </div>
  </div>
</div>