config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#top'
  get 'static_pages/terms', as: :terms
  get 'static_pages/privacy', as: :privacy
  get 'login', to: 'user_sessions#new', as: :login
  post 'login', to: "user_sessions#create"
  delete 'logout', to: 'user_sessions#destroy', as: :logout
  get 'results', to: "results#index"
  get 'rankings', to: "rankings#index"
  post '/google_login/callback', to: 'google_login#callback'

  resources :users
  get 'users/:id/change_password', to: "users#change_password", as: :change_password

  resources :password_resets, only: %i[new create edit update]

  resources :recordings, only: %i[new create] do
    resources :text_analyses, only: %i[new create]
    resources :results, only: %i[new create show]
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/views/shared/_after_login_header_link.html.erb
<li class="nav-item dropdown dropdown-slide">
  <a href="#" class="nav-link me-2" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
    <%= image_tag 'icon_user', class: "icon rounded-circle me-2" %>
  </a>
  <div class="dropdown-menu dropdown-menu-end">
    <div class="dropdown-item"><%= current_user.name %></div>
    <div class="dropdown-divider"></div>
    <%= link_to t('defaults.my_page'), results_path, class: 'dropdown-item' %>
    <%= link_to t('defaults.account_setting'), edit_user_path(current_user), class: 'dropdown-item' %>
    <div class="dropdown-divider"></div>
    <%= button_to t('defaults.logout'), logout_path, class: 'dropdown-item', method: :delete %>
  </div>
</li>

app/views/shared/_before_login_header_link.html.erb
<li class="nav-item">
  <%= link_to t('defaults.register'), new_user_path, class: 'nav-link' %>
</li>
<li class="nav-item">
  <%= link_to t('defaults.login'), login_path, class: 'nav-link' %>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer-bottom footer-color mt-3 pt-3 pb-3">
  <div class="container">
    <div class="row">
      <div class="d-flex flex-column align-items-start">
        <%= link_to t('defaults.terms'), terms_path, class: 'link_to text-center' %>
        <%= link_to t('defaults.privacy'), privacy_path, class: 'link_to text-center' %>
      </div>
      <div class="d-flex justify-content-end flex-column align-items-end">
        <div>© 2022. filler checker</div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_google_login.html.erb
<div class="mt-2">
  <script src="https://accounts.google.com/gsi/client" async defer></script>
  <div id="g_id_onload"
    data-client_id="<%= ENV['GOOGLE_CLIENT_ID'] %>"
    data-login_uri="<%= google_login_callback_path %>"
    data-auto_prompt="false">
  </div>
  <div class="g_id_signin"
    data-type="standard"
    data-size="large"
    data-theme="outline"
    data-text="sign_in_with"
    data-shape="rectangular"
    data-logo_alignment="left">
  </div>
</div>

app/views/shared/_header.html.erb
<header class="header header-color index-top">
  <nav class="navbar navbar-expand">
    <ul class="navbar-nav me-auto">
      <li class="nav-item">
        <%= link_to root_path, class: 'navbar-brand ms-3' do %>
          <%= image_tag 'logo', class: 'img-fluid logo' %>
        <% end %>
      </li>
    </ul>
    <ul class="navbar-nav ms-auto">
      <% if logged_in? %>
        <%= render 'shared/after_login_header_link' %>
      <% else %>
        <%= render 'shared/before_login_header_link' %>
      <% end %>
    </ul>
  </nav>
</header>