config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#top'
  get 'static_pages/terms', as: :terms
  get 'static_pages/privacy', as: :privacy
  get 'login', to: 'user_sessions#new', as: :login
  post 'login', to: "user_sessions#create"
  delete 'logout', to: 'user_sessions#destroy', as: :logout
  get 'results', to: "results#index"
  get 'rankings', to: "rankings#index"
  post '/google_login/callback', to: 'google_login#callback'

  resources :users
  get 'users/:id/change_password', to: "users#change_password", as: :change_password

  resources :password_resets, only: %i[new create edit update]

  resources :recordings, only: %i[new create] do
    resources :text_analyses, only: %i[new create]
    resources :results, only: %i[new create show]
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :recording

  validates :filler_count, presence: true

  def filler_interval
    return 9999 if self.filler_count.to_i == 0
    (self.recording[:length] / self.filler_count.to_f).round(1)
  end

  def filler_interval_text
    return 'フィラーなし' if self.filler_count.to_i == 0
    "#{self.filler_interval}秒に1回"
  end

  def most_frequent_filler_word
    self.most_frequent_filler.gsub('%', '')
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  skip_before_action :require_account, only: %i[new create show]

  def index
    @results = Result.joins(:recording).where("recordings.user_id = ?", current_user.id).order(created_at: :desc)
  end

  def new
    @text_analysis = TextAnalysis.where(recording_id: params[:recording_id])
    @filler_count = @text_analysis.filler_count
    @most_frequent_filler = @text_analysis.most_frequent_filler
    @result = Result.new
  end

  def create
    @result = Result.new(result_params)
    if @result.save
      redirect_to recording_result_path(result_params[:recording_id], 1), success: t('defaults.message.successed_analyze')
    else
      flash.now[:danger] = t('.failed')
      redirect_to new_recording_path, danger: t('defaults.message.failed_analyze')
    end
  end

  def show
    @recording = Recording.find(params[:recording_id])
    @result = Result.find_by(recording_id: @recording.id)
    not_authenticated unless @recording.user_id == current_user.id
    @tweet_url = tweet_url(@result)
  end

  private

  def result_params
    params.require(:result).permit(:recording_id, :filler_count, :most_frequent_filler)
  end

  def tweet_url(result)
    params = URI.encode_www_form({
      'url': request.base_url, 
      'text': tweet_text(result), 
      'hashtags': 'えーとチェッカー'
    })
    return "https://twitter.com/share?#{params}"
  end

  def tweet_text(result)
    texts = []
    texts[0] = "つなぎ言葉（フィラー）の回数は#{result.filler_interval_text}でした\n\n"
    
    if result.filler_interval == 9999 # never
      texts[0] = "つなぎ言葉（フィラー）はありませんでした！\n\n"
      texts[1] = "#{current_user.name}は\n一切のよどみなく人にものごとを伝えられる\nスピーチマスターです！"
    else
     if result.filler_interval < 5
      texts[1] = "#{result.most_frequent_filler_word}・・・、\n#{current_user.name}はフィラー癖が多いほうです。\n善処します"
     else
      texts[1] = "#{current_user.name}は\nたまに#{result.most_frequent_filler_word}・・・といってしまいますが、\n気になるほどではないです。"
     end
    end

    texts[2] = "\n\nえーと…を言わずに話せるか試そう！"
    return texts.sum
  end
end

app/views/results/_form.html.erb
<%= form_with id: "result-form", model: [@recording, @result], url: recording_results_path, local: true do |f| %>
  <div class="form-group">
    <%= f.label :recording_id %>
    <%= f.text_field :recording_id, id: 'result-recording-id', value: params[:recording_id] %>
    <%= f.label :filler_count %>
    <%= f.text_field :filler_count, id: 'result-filler-count', value: @filler_count %>
    <%= f.label :most_frequent_filler %>
    <%= f.text_field :most_frequent_filler, id: 'result-most-frequent-filler', value: @most_frequent_filler[:word] %>
  </div>
  <%= f.submit class: 'btn btn-primary', id: 'regist-result' %>
<% end %>

app/views/results/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="container mt-5">
  <p class="h2 text-center"><%= t('.log') %></p>
  <div class="d-flex justify-content-center mt-3">
    <%= link_to t('.new_challenge'), new_recording_path, class: 'btn btn-warning btn-circle col-4' %>
  </div>
  <div class="d-flex justify-content-center mt-5">
    <div class="col-12 col-lg-10">
      <canvas id="frequencyChart"></canvas>
    </div>
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.9.1/chart.min.js" integrity="sha512-ElRFoEQdI5Ht6kZvyzXhYG9NqjtkmlkfYk0wr6wHxU9JEHakS7UJZNeml5ALk+8IKlU6jDgMabC3vkumRokgJA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

  <div class="d-flex justify-content-center mt-5">
    <div class="col-12 col-lg-8 table-responsive">
      <table class="table styled-table text-nowrap">
        <thead class="thead-light main-color">
          <tr>
            <th><%= Theme.human_attribute_name(:title) %></th>
            <th><%= Result.human_attribute_name(:filler_count) %></th>
            <th><%= t('.frequency') %></th>
            <th class="display-none"><%= t('.frequency_per_second') %></th>
            <th><%= User.human_attribute_name(:name) %></th>
            <th><%= t('.recording_date') %></th>
            <th></th> <%#= 空のヘッダー %>
          </tr>
        </thead>
        <tbody id="result-table-body">
          <% @results.each do |result| %>
            <tr>
              <th scope="row"><%= result.recording.theme[:title] %></th>
              <td><%= result.filler_count %></td>
              <td><%= result.filler_interval_text %></td>
              <td class="frequency display-none"><%= 1/result.filler_interval %></td>
              <td><%= result.recording.user[:name] %></td>
              <td class="created_at"><%= I18n.l(result.created_at) %></td>
              <td class="detail"><%= link_to t('.detail'), recording_result_path(result.recording, 1), class: 'link_to' %></th>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<%= javascript_include_tag "frequencyChart" %>

app/views/results/new.html.erb
<div hidden>
  <h2>reultsテーブルに登録</h2>
  <%= render 'form' %>
</div>

app/views/results/show.html.erb
<% content_for(:title, t('.title')) %>
<div class="container mt-5 d-flex flex-column align-items-center">
  <p class="h2">
    <%= t('.result') %>
      <%= link_to @tweet_url, class: 'ms-2 btn btn-primary', target: '_blank' do %>
        <i class="bi bi-twitter"></i>
        <%= t('.share_twitter') %>
      <% end %>
  </p>
  <%# <p class="h4 mt-3">あなたのフィラー癖は</p> %>

  <div class="d-flex justify-content-center mt-3">
    <div class="card text-center col-5 h4 me-3">
      <div class="card-header main-color">
        <%= Result.human_attribute_name(:filler_count) %>
      </div>
      <div class="card-body pt-5 pb-5">
        <p><%= "#{t('defaults.sum')} #{@result.filler_count} #{t('defaults.count')}" %></p>
        <p class="h6"><%= @result.filler_interval_text %></p>
      </div>
    </div>
    <div class="card text-center col-5 h4">
      <div class="card-header main-color">
        <%= t('.most_frequent_filler') %>
      </div>
      <div class="card-body pt-5 pb-5">
        <p><%= "「#{@result.most_frequent_filler.gsub('%','')}」" %></p>
      </div>
    </div>
  </div>
  <div>
    <% if @recording.audio.present? %>
      <%= audio_tag(url_for(@recording.audio), controls: true) %>
    <% end %>
  </div>

  <p class="h2 mt-5 mb-3"><%= t('defaults.how_to_speak_smoothly') %></p>
  <div class="d-flex flex-column col-12 col-lg-6">
    <div class="card">
      <div class="card-header sub-color h5">
        <%= t('techniques.accept_silence.heading') %>
      </div>
      <p class="m-1"><%= t('techniques.accept_silence.description') %></p>
    </div>
    <div class="card mt-3">
      <div class="card-header sub-color h5">
        <%= t('techniques.prepare_speech.heading') %>
      </div>
      <p class="m-1"><%= t('techniques.prepare_speech.description') %></p>
    </div>
    <div class="card mt-3">
      <div class="card-header sub-color h5">
        <%= t('techniques.be_used.heading') %>
      </div>
      <p class="m-1"><%= t('techniques.be_used.description') %></p>
    </div>
  </div>
  <%= link_to t('.to_my_results'), results_path, class: 'btn btn-warning col-4 mt-5' %>
</div>