config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#top'
  get 'static_pages/terms', as: :terms
  get 'static_pages/privacy', as: :privacy
  get 'login', to: 'user_sessions#new', as: :login
  post 'login', to: "user_sessions#create"
  delete 'logout', to: 'user_sessions#destroy', as: :logout
  get 'results', to: "results#index"
  get 'rankings', to: "rankings#index"
  post '/google_login/callback', to: 'google_login#callback'

  resources :users
  get 'users/:id/change_password', to: "users#change_password", as: :change_password

  resources :password_resets, only: %i[new create edit update]

  resources :recordings, only: %i[new create] do
    resources :text_analyses, only: %i[new create]
    resources :results, only: %i[new create show]
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create destroy]
  skip_before_action :require_account, only: %i[destroy]

  def new
  end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_back_or_to results_path, success: t('.success')
    else
      flash.now[:danger] = t('.failed')
      render :new, status: :unprocessable_entity
    end
  end
  
  def destroy
    logout
    redirect_to root_path, success: t('.success')
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= form_with model: @user, local: true do |f| %>
  <div class="form-group">
    <%= f.label :email, t('.email') %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password, t('.password') %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <%= f.submit t('defaults.login'), class: 'btn btn-info btn-circle mt-3' %>
<% end %>

app/views/user_sessions/_google_login.html.erb
<div class="mt-2">
  <script src="https://accounts.google.com/gsi/client" async defer></script>
  <div id="g_id_onload"
    data-client_id=<%= ENV['GOOGLE_CLIENT_ID'] %>
    data-login_uri=<%= google_login_callback_path %>
    data-auto_prompt="false">
  </div>
  <div class="g_id_signin"
    data-type="standard"
    data-size="large"
    data-theme="outline"
    data-text="sign_in_with"
    data-shape="rectangular"
    data-logo_alignment="left">
  </div>
</div>

app/views/user_sessions/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class=" col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <p class="h2"><%= t('.title') %></p>
      <%= render 'form', user: @user %>
      <%= render 'shared/google_login' %>
      <div class='text-center d-flex justify-content-center mt-2'>
        <%= link_to t('.to_register_page'), new_user_path, class: 'me-3 link_to' %>
        <%= link_to t('.password_forget'), new_password_reset_path, class: 'link_to' %>
      </div>
    </div>
  </div>
</div>